### ISSUE TITLE
unable to run this project on my system

### ISSUE THREAD

**Issue by Sawan-Kag** [geisterfurz007/random-alarm#15] opened 2021-03-21 06:23 UTC
when i am trying to run i am getting error in stores folder

Target of URI hasn't been generated: 'observable_alarm/observable_alarm.g.dart'.
Target of URI hasn't been generated: 'searchable_selection.g.dart'.

**Comment by mvarendorff** [comment] 2021-03-23 11:19
Duplicate of #13
Use build_runner to generate generated files.

**Closed as completed by mvarendorff** 2021-03-23 11:19 UTC
